#defaults

if [ -z "$HISTFILE" ]; then
  HISTFILE=$HOME/.zsh_history
fi

HISTSIZE=5000
SAVEHIST=5000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history # share command history data

#GIT
alias gs='git status'
alias gcm='git commit -m'
alias ga='git add'
alias gl='git log --graph --abbrev-commit --decorate --date=relative --all'
alias gcof='git checkout $(git branch | fzf)'
alias gco='git checkout'
alias glc='git shortlog -s -n'
alias gconflicts='git diff --name-only --diff-filter=U'

alias pull='git pull --rebase'
alias push='git push'

fpath=(~/.zsh/completion $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)
. $(brew --prefix)/share/zsh/site-functions

#IMPORT FILES
[ -f $HOME/.zsh_profile ] && source $HOME/.zsh_profile
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export HOMEBREW_NO_ANALYTICS=1

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
